### PR TITLE
Merge Nyanotrasen

### PR DESCRIPTION
**Pull request by ZeroDayDaemon**

### CODE REVIEW

**Comment by ZeroDayDaemon** [comment]
Delta-v is an open-source enterprise video game designed to be 100% bug-for-bug compatible with Nyanotrasen®.

**Comment by ZeroDayDaemon** [comment]
Delta-v rebuilds sources directly from Nyanotrasen®, so you can bet your best dollar that you'll have a super stable experience, no matter the use-case.

**Comment by ZeroDayDaemon** [comment]
### Production Ready
Delta-v is enterprise-ready, providing solid stability with regular updates and a 10-year support lifecycle, all at no cost.
### Community Supported
The community, sponsors, and partners have invested with long-term commitments to ensure the project stays with the community.
### Easy Migration
Migrate from other Enterprise Space Station 14 distributions without sweating it. We provide an easy-to-use migration script, free of charge.

**Comment by DebugOk** [comment]
Isn't that Rocky Linux's thing?

**Pull request merged**
