### PR TITLE
Added the ghost hotel day map

### PR DESCRIPTION
**Pull request by ShatteredSwords**
**Changelog**

:cl:
- add: Add more things related to the ghost bar

### CODE REVIEW

**Review by DebugOk — CHANGES_REQUESTED** [review]
Test failure is related to the map, rerunning is pointless until its fixed

**Comment by ShatteredSwords** [comment]
No idea what's wrong with it but guess I'll find out

**Comment by DebugOk** [comment]
\>Merges master twice
\>Still out of date
Most real github experience
image

**Comment by ShatteredSwords** [comment]
> >Merges master twice >Still out of date Most real github experience image

GRAH

**Comment by DebugOk** [comment]
Just leave it be, it doesn't really matter for map changes. Just let the tests finish :blunt:

**Comment by DebugOk** [comment]
Are you trying to map a ClothingOuterHardsuitERTMedical? Its the only null reference I saw in my quick skim over the file

**Comment by ShatteredSwords** [comment]
> Are you trying to map a ClothingOuterHardsuitERTMedical? Its the only null reference I saw in my quick skim over the file

Yes, for the hotel owner. I can replace it though

**Comment by DebugOk** [comment]
Just try getting rid of it for now, see if thats the issue or not.

**Comment by DebugOk** [comment]
Friendly reminder that you can run the build & test stuff locally, it just runs these commands.

`dotnet build` only if it fails for whatever reason on the next commands
`dotnet build --configuration DebugOpt --no-restore /p:WarningsAsErrors=nullable /m`
`dotnet test --no-build --configuration DebugOpt Content.Tests/Content.Tests.csproj -- NUnit.ConsoleOut=0`
`dotnet test --no-build --configuration DebugOpt Content.IntegrationTests/Content.IntegrationTests.csproj -- NUnit.ConsoleOut=0`

**Comment by ShatteredSwords** [comment]
Yes but you see, I would rather get email notifications when something goes wrong

**Comment by DebugOk** [comment]
> Yes but you see, I would rather get email notifications when something goes wrong

Running it locally means it finishes in under 3 minutes (assuming a decent pc). The machines Github Actions run on aren't the fastest

**Comment by DebugOk** [comment]
Nope, it wasn't that. I'll be able to take a closer look soon:tm:

**Comment by ShatteredSwords** [comment]
Tests on my side work

**Comment by ShatteredSwords** [comment]
I will eat you Linux

**Review by DebugOk — CHANGES_REQUESTED** [review]
image
Why are these vacuum markers instead of their respective N2/O2 markers

image
Antique power cells? What for?

You should really color the pipes, heres a copy paste explaining how
> To color all pipes in a pipe network use colornetwork [entity id] Pipe [color] where the entity ID is any uid of a pipe within a connected network of pipes (Use View Variable on a pipe to find this), and color is a color hex starting with #. For example for a waste loop you could use #990000 as a pleasing dull red and for a fresh air loop #0055cc for a popping subdued blue.

The pipes is the only thing I'd really like to see changed, as the vacuum markers aren't a big deal and the antique power cells shouldn't matter assuming no one can ever get to them from the station

**Pull request closed without merging**
