### PR TITLE
Adding PDAs to the PDA vendor

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR

Adds basic department PDAs to the HOP Ptech vendor

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: VMSolidus
- add: Basic department PDAs can now be obtained from the HOP's Ptech vendor

### CODE REVIEW

**Comment by JustTNE** [comment]
This is definitely something I'd like to see merged! Changing profession to medical without a medical PDA is just not the best of experiences in general. Thanks for making this PR, we talked about it in game already!

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by DebugOk** [comment]
Changelog entry is invalid, and wont get added if I merge this without it being fixed

**Comment by VMSolidus** [comment]
Shoot, whats the tag I need to add to it to get the changelog correct?

**Comment by Colin-Tel** [comment]
> Shoot, whats the tag I need to add to it to get the changelog correct?

do this:

"- add: Added fun!"
displays as
- add: Added fun!

**Comment by VMSolidus** [comment]
Got it! Thanks!

**Pull request merged**
