### PR TITLE
Gunmetal

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

Adds several new drinks, sprites for moonshine, new jumpsuit and jacket, and a new poster.

**Media**

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: TadJohnson00, ShatteredSwords, DinkusMcsplinkus
- add: Added several new drinks, including Gunmetal, a drink that incorporates welding fuel, rum, and cream.
- tweak: Moonshine now has a real sprite.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
greentext pls

**Comment by TadJohnson00** [comment]
Any idea what's causing the issue, Debug?

**Comment by ShatteredSwords** [comment]
There is a possibility that the Mojito (not your drinks) is broken and making the game angry.

**Comment by TadJohnson00** [comment]
not the mojito, top fifteen drinks fr fr ;-;

**Comment by TadJohnson00** [comment]
Okay but mojito fanclubbery aside, what am I supposed to do here

**Comment by TadJohnson00** [comment]
GIVE ME THE GREEN GODDAMN IT

**Comment by TadJohnson00** [comment]
did this little shit just fail me because the tests were taking too long

**Comment by DebugOk** [comment]
> did this little shit just fail me because the tests were taking too long

It did, yes

**Comment by TadJohnson00** [comment]
This is a jor moment if I ever saw one

**Review by DebugOk — APPROVED** [review]
If tests passed its probably fine :clueless:

**Pull request merged**
