### PR TITLE
Loadouts system (Work in progress)

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
Still a heavy WIP at this point, just putting it up here so other people can see

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by DebugOk** [comment]
Haha nice pull request number 69!!1!!1

**Comment by DebugOk** [comment]
@DEATHB4DEFEAT considering I ~~stole~~ copied 100% of this code(so far) from Park I'm gonna be requesting a review from you, as I dont think I need to modify much of that anymore

**Comment by DEATHB4DEFEAT** [comment]
> @DEATHB4DEFEAT considering I ~~stole~~ copied 100% of this code(so far) from Park I'm gonna be requesting a review from you, as I dont think I need to modify much of that anymore

I'll review it later today, the system should work perfectly fine but I definitely need to clean some of my code if you haven't already

**Comment by DebugOk** [comment]
> > @DEATHB4DEFEAT considering I ~~stole~~ copied 100% of this code(so far) from Park I'm gonna be requesting a review from you, as I dont think I need to modify much of that anymore
> 
> I'll review it later today, the system should work perfectly fine but I definitely need to clean some of my code if you haven't already

Most of this was just directly copied with only enough changes to exclude what we didn't need here

**Comment by DEATHB4DEFEAT** [comment]
I've been wanting to pr this to wizden, I should probably do that instead of this tbh.

Do you mind if make edits to this directly or should I just review?

**Comment by DebugOk** [comment]
Feel free to

**Comment by DebugOk** [comment]
@DEATHB4DEFEAT Did you ever get to work on sending this to wizden or where you going to make changes here?

**Comment by DEATHB4DEFEAT** [comment]
> @DEATHB4DEFEAT Did you ever get to work on sending this to wizden or where you going to make changes here?

I'll pr to wizden in a bit

**Comment by DEATHB4DEFEAT** [comment]
https://github.com/space-wizards/space-station-14/pull/17517

**Comment by DebugOk** [comment]
Should be done by wizden, can reopen if they dont merge it

**Pull request closed without merging**
