### PR TITLE
Changelog bot

### PR DESCRIPTION
**Pull request by DEATHB4DEFEAT**
## GitHub Environment Variables needed
Sub-headers have a linked guide on where to put these variables, items have an example in (parenthesis)

### [Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
- BOT_TOKEN - A Personal Access Token with `Contents - Write` access

### [Vars](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows)
- CHANGELOG_BRANCH - Which branch to push the changelog updates to (master)
- CHANGELOG_DIR - The path to the changelog file (Resources/changelog/changelog.yml)
- CHANGELOG_MESSAGE - The commit comment (Automatic Changelog Update)
- CHANGELOG_USER - For git metadata, can probably be whatever?
- CHANGELOG_EMAIL - For git metadata, use the bot account's email

### CODE REVIEW

**Review by DebugOk — APPROVED** [review]
Epic, I added the variables and stuff too so it should try running on merge, and then not do anything because theres no CL entry

**Comment by DebugOk** [comment]
Time to add package-lock.json to gitignore

**Comment by DEATHB4DEFEAT** [comment]
> Time to add package-lock.json to gitignore

good idea, but it is set to only add `*.yml` files on commit :)

**Comment by DebugOk** [comment]
```
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Tools/changelog/package-lock.json
nothing added to commit but untracked files present (use "git add" to track)
Error: Process completed with exit code 1.
```
https://github.com/DeltaV-Station/Delta-v/actions/runs/5194769860/jobs/9366812019

**Comment by DEATHB4DEFEAT** [comment]
> ```
> On branch master
> Your branch is up to date with 'origin/master'.
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	Tools/changelog/package-lock.json
> nothing added to commit but untracked files present (use "git add" to track)
> Error: Process completed with exit code 1.
> ```
> 
> https://github.com/DeltaV-Station/Delta-v/actions/runs/5194769860/jobs/9366812019

an expected failure, there was no CL to commit so it doesn't commit
I don't know if I can get it to fail quietly on this step

**Comment by DebugOk** [comment]
> > ```
> > On branch master
> > Your branch is up to date with 'origin/master'.
> > Untracked files:
> >   (use "git add <file>..." to include in what will be committed)
> > 	Tools/changelog/package-lock.json
> > nothing added to commit but untracked files present (use "git add" to track)
> > Error: Process completed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/DeltaV-Station/Delta-v/actions/runs/5194769860/jobs/9366812019
> 
> an expected failure, there was no CL to commit so it doesn't commit I don't know if I can get it to fail quietly on this step

If its an expected failure, just set `continue-on-error: true`. That way it'll always be marked as completed

**Comment by DEATHB4DEFEAT** [comment]
> > > ```
> > > On branch master
> > > Your branch is up to date with 'origin/master'.
> > > Untracked files:
> > >   (use "git add <file>..." to include in what will be committed)
> > > 	Tools/changelog/package-lock.json
> > > nothing added to commit but untracked files present (use "git add" to track)
> > > Error: Process completed with exit code 1.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://github.com/DeltaV-Station/Delta-v/actions/runs/5194769860/jobs/9366812019
> > 
> > 
> > an expected failure, there was no CL to commit so it doesn't commit I don't know if I can get it to fail quietly on this step
> 
> If its an expected failure, just set `continue-on-error: true`. That way it'll always be marked as completed

alright should I make another pr

**Comment by DebugOk** [comment]
> alright should I make another pr

Seems a bit excessive for one small change, I could just as easily push it directly without a pr :blunt:

**Comment by DEATHB4DEFEAT** [comment]
> > alright should I make another pr
> 
> Seems a bit excessive for one small change, I could just as easily push it directly without a pr :blunt:

:godmode:

**Comment by DebugOk** [comment]
Shouldn't fail now when there's no changelog (or anything else goes wrong). Thanks again!

**Pull request merged**
