### PR TITLE
Vulpkanin sprite rework and more customization options

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR
This does the following:
- Moves all files related to Vulpkanin into the DeltaV folders.
  - Replaces all mentions of HumanoidFox with Vulpkanin.
  - Replaces all mentions of "fox ---" with "vulpkanin ---" for body parts.
  - Removes sprites that are unused by SS14 at this time; groin, fat variants, square(?).
- Fix Vulpkanin not having default ears and them not being required.
- Add a Vulpkanin version of the pie sprite when they get clowned.
- Replace/Tweak the Vulpkanin sprites for a cleaner look while _trying_ to keep it relatively similar.
  - Replace all the markings to match the new color scheme for uniformity and rename them accordingly.
- Add first and last names taken from Paradise Station.
- Add 12 new tails, with variants: 
  - Static only: Fennec, Fluffy, Fox 2, Fox 3, Husky, Long, Otie, Vulp alt
  - Animated only: Corgi, Dalmatian
  - Static and Animated variants: Bushy, Fox, Vulp, Coyote
- Add additional markings for old tails and new.
- Add 10 new ears, with variants: Coyote, Dalmatian, Fennec, Fox, Jackal, Msai, Otie, Shock, Terrier, Wolf
  - Add additional markings for old ears.
- Add 13 new head markings: Different types of muzzles and stripes. 
- Add 3 new overlays for hands and feet: Crest, Point, Fade.
- Add 21 new hair and 4 facial hair specific to the Vulpkanin.
- Add the Vulpkanin to the metempsychotic humanoid pool.
- Give the Vulpkanin talk sounds.

**Media**
lazy see the RSI Diff Bot

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added a bunch of new customisation options for the Vulpkanin.
- tweak: Tweaked the Vulpkanin sprites.

### CODE REVIEW

**Comment by DebugOk** [comment]
> RSI Diff Bot; head commit https://github.com/DeltaV-Station/Delta-v/commit/b3e343748343b27d1f05c872997501904f0cfe09 merging into https://github.com/DeltaV-Station/Delta-v/commit/e2f6ab50edb226426e6849db62bafbb5de1e913e
This PR makes changes to 1 or more RSIs. Here is a summary of all changes:

What a great summary! Thanks github-actions

**Comment by FluffiestFloof** [comment]
I think it's good for review.

**Comment by DebugOk** [comment]
Epic

**Review by DebugOk — APPROVED** [review]
The talk sounds sound a bit weird in my opinion, but that doesn't really matter. Its cool regardless

**Comment by FluffiestFloof** [comment]
> The talk sounds sound a bit weird in my opinion, but that doesn't really matter. Its cool regardless

Oh yeah, they are from Goonstation and were meant for their Pug specie. I just stumbled upon them and why not.
Could always just be removed if they are too weird/annoying.

**Comment by DebugOk** [comment]
> > The talk sounds sound a bit weird in my opinion, but that doesn't really matter. Its cool regardless
> 
> Oh yeah, they are from Goonstation and were meant for their Pug specie. I just stumbled upon them and why not. Could always just be removed if they are too weird/annoying.

I doubt it'll be a problem, they should be fine

**Pull request merged**
