### PR TITLE
Improve changelog system

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
This will allow us to use 2 seperate changelogs files, and not run into the issue where mismatching IDs will result in one or the other not showing up as "NEW!". This will, however, not show something as new if it was added to the changelog _after_ some other changelog entry with a later date was read. Doing that would require using both the id and date.

There is also a regex check in place to make sure this wont crash if it finds an ID in the last read changelog file, but it does rely on the `server.id` CVar being set properly, as not doing so might cause issues when another server using the old system tries to read the file.

**Changelog**
 
:cl: Debug
- tweak: Made the changelog system better

### CODE REVIEW

**Comment by DebugOk** [comment]
@ZeroDayDaemon Have you had a chance to review this yet? I'll have to write a changelog for the thing tomorrow and it'd be nice to know before then

**Comment by ZeroDayDaemon** [comment]
If you've tested it and it works fine you can go ahead and merge it, it looks fine me to me from a quick lookover

**Review by ZeroDayDaemon — APPROVED** [review]

**Comment by DebugOk** [comment]
In game it works fine, but it heavily depends on if `server.id` is set properly. If it isn't and you join another server it'll cause some issues. Nothing game crashing but it wont work as intended

**Comment by ZeroDayDaemon** [comment]
Uhhh if it can cause issues with other servers might want to wait on it then, cant guarantee server.id is set properly in every one.

**Comment by DebugOk** [comment]
The only real issue it causes is an error in the console, and always showing the changelog as new

**Comment by ZeroDayDaemon** [comment]
> The only real issue it causes is an error in the console, and always showing the changelog as new

Yeah, but we dont want to mess with people's clients in ways that affects other servers in any way

**Comment by DebugOk** [comment]
Thats fair, I'll write something to make sure that cant happen, even if the id isn't set

**Comment by DebugOk** [comment]
It wont cause any issues if the last seen changelog thing is invalid for this code, because it checks if its in the right format before attempting to convert it. But the original implementation lacks that, and you cant convert ISO 8061 to an integer. But just making sure this uses another file, even when the id isn't set, should prevent this from ever being an issue

**Comment by DebugOk** [comment]
Everything should work, but I have my doubts about the changelog.py working. Not that it matters because it didn't before this either

**Pull request merged**
