### PR TITLE
Contractor Equipment

### PR DESCRIPTION
**Pull request by LittleBuilderJane**
## About the PR 
Adds a uniform, beret, backpack, magboots and three variants of Contractor Hardsuits, being unique variants of existing suits intended for a neutral, third-party group. They are meant to primarily be used in Events.
**Media**

image
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Schiene
- add: Couple of Contractor variants of Clothes and Hardsuits.

### CODE REVIEW

**Review by DebugOk — CHANGES_REQUESTED** [review]
Unless also PR'd on Wizden, textures and prototypes should be put into their forks folder. `/Resources/Textures/DeltaV/...` or `/Resources/Prototypes/DeltaV/...`

Since this is also a PR on Nyano, https://github.com/Nyanotrasen/Nyanotrasen/pull/1451, it should be placed in `/Resources/Textures/Nyanotrasen` `/Resources/Prototypes/Nyanotrasen` unless you intend for it to be unique to Delta.

PR https://github.com/DeltaV-Station/Delta-v/pull/30 should be a good example of how textures and prototypes for downstreams are put in

**Comment by FluffiestFloof** [comment]
The last three sprites look kinda weird... First one is neat tho.

**Comment by TadJohnson00** [comment]
image
If you could change this, it would help to avoid confusion with the latest fedoras added.

Also yeah, I'd agree with Floofers that the sprites look a little off-colour; but then again, I'm not in charge of art direction.

**Comment by LittleBuilderJane** [comment]
I fixed the Fedora stuff, but idk how to move the stuff into the DeltaV Folder without breaking the base stuff, unfortunately, as it overwrites the base stuff.

**Comment by Jerryaqua** [comment]
the first set of clothes looks cool, but the last three are very strange looking and do not fit with the same scheme, might be best if you work on them still

**Comment by leonardo-dabepis** [comment]
I agree with what others have said about the latter three sprites looking off. If you want advice on different ways you could fix the sprites, you can message me on Discord. The big thing I notice right off the bat is the lack of contrast in the different shades of green, all the greens in the later three sprites are very close in value and so they kind of blend together, which makes the sprites look flat and undetailed. I think just adding some darker values in there may do the trick, but again you can always message me on Discord for more in-depth advice.

**Comment by TadJohnson00** [comment]
Given how we recently also received a quantity of mercenary equipment, I'd additionally advise reworking your planned additions around those, as well as your spriting colour palette; that is, if you're still working on this PR.

**Comment by DebugOk** [comment]
Closing as stale

**Pull request closed without merging**
