### PR TITLE
mail teleporter time on examine

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- show seconds until next teleport when examined
- also moved update into its own system since its not related to mail handling
  ideally would move all the teleporter related stuff but theres a lot and it would probably break tests

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Mail teleporters now show time until next teleport when examined.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Shouldn't this be upstreamed since it's touching on Nyano code?

**Comment by deltanedas** [comment]
nyano is noob

**Comment by DebugOk** [comment]
> Shouldn't this be upstreamed since it's touching on Nyano code?

I do agree with floofers here, this should probably be upstreamed

**Comment by deltanedas** [comment]
pro

**Pull request closed without merging**
