### PR TITLE
Tweak Typewriter, add guns to cargo

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

Tweaks the Typewriter stats and sounds, so it's a little more inaccurate in longer bursts and makes a much nicer gunshot effect.
Adds mobster entity, so you can make easy ghost roles - and remove mafioso role, because the mafia is now a democracy.
Adds Mk32 Universal and Mark 1 Rifle crates to cargo, and both gun safes for mapping.

**Media**

I'm pretty sure this doesn't need any media. All it'd show is secure weapons crates, an .ogg file, and two new entries in the entity spawn menu.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Mk32 Universal combat handguns and Mark 1 rifles are now purchasable from cargo.
- tweak: Typewriter now has a much more badass firing sound, fires faster, and is more inaccurate with longer bursts.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
Debug where do the things goooo

**Review by DebugOk — CHANGES_REQUESTED** [review]
> Debug where do the things goooo

Nukie stuff is in Resources/Prototypes/Roles/Jobs/Fun/misc_startinggear.yml

So you should put the mafia stuff in Resources/Prototypes/DeltaV/Roles/Jobs/Fun/misc_startinggear.yml (or another startinggear file if you really want to). Where you currently have these files is intended for something like https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Roles/Antags/nukeops.yml

**Comment by TadJohnson00** [comment]
Aightio, change has been made. Fingers crossed for greentext.

**Comment by TadJohnson00** [comment]
it's all green baybee

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
