### PR TITLE
HoP Mess Kit, Inspection Items, E-Cutlass sprit

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

This is the first instalment in a line of many planned additions to the game's current uniforms and clothing items. This particular PR features clothing pertaining to Adym Ryuzo, some dress uniforms, and a change to the e-cutlass sprites to fit the planned artstyle.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image
ecutlass

**Changelog**

:cl:
- add: Added HoP mess kit, inspection items, and flak jackets.
- tweak: Changed e-cutlass sprites to fit planned artstyle, replaced detective vest with press flak jacket in RepDrobe.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Since the Ryuzo clothing items are admin only, I suggest adding `suffix: No Map` to avoid potential accidental usage by mappers.

**Comment by DebugOk** [comment]
I'm not so sure about adding clothing for 1 character, that sorta stuff could just as easily be prototype loaded in

**Comment by DebugOk** [comment]
If it were to be left in, it should at least have a creative name and a suffix like Floofers mentioned.

**Comment by TadJohnson00** [comment]
Pugi specifically asked for the Ryuzo sprites to be added in as far as I'm aware, but I'll add the [ADMIN ONLY / DO NOT MAP] suffix to them.

**Comment by DebugOk** [comment]
Cool that she asked for it, but they should at least have a name that isn't a character name

**Comment by TadJohnson00** [comment]
I'll give her a ping. Is it alright if the prototypes are named "Ryuzo" but the in-game names are unique?

**Comment by DebugOk** [comment]
Prototype names aren't visible to the player anyways, so that should be fine

**Comment by DebugOk** [comment]
Yaml linter appears to be failing, cant merge until thats fixed

**Comment by TadJohnson00** [comment]
Should be fixed now, let's see this greentext baybee

**Comment by DebugOk** [comment]
Yaml linter passed, of course builds are still gonna fail because they can

**Comment by TadJohnson00** [comment]
Will they get fixed this century?

**Comment by DebugOk** [comment]
Probably soon:tm:, upstream has already identified whats going wrong last I checked

**Comment by DebugOk** [comment]
Also, in the future, try making a seperate branch on your forked repo for making PRs, it saves you a ton of trouble

**Pull request merged**
