### PR TITLE
New Shotgun and Battle rifle for security

### PR DESCRIPTION
**Pull request by Jerryaqua**
## About the PR

**Media**

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A old Battle rifle was taken out of storage and is being sent to Staions to help refill the armory at a lower cost. A new high-tech shotgun is also being sent out as well.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
> \- add: A old Battle rifle was taken out of storage and is being sent to Staions to help refill the armory at a lower cost. A new high tech shotgun is also being sent out as well

\- add: A**n** old **b**attle rifle was taken out of storage and is being sent to **s**ta**t**ions to help refill the armory at a lower cost. 
**- add: Along with the new battle rifle, we will also be sending out a high-tech shotgun.**

**Comment by Hyenh** [comment]
You didn't write anything down for the copyright in the Vulcan meta.json.

**Comment by Jerryaqua** [comment]
Well damn I used the old one, I'll be sure to fix that

**Review by TadJohnson00 — COMMENTED** [review]
A couple of things: for the cargo crates, you'll most likely need to add descriptions and names for the cargo console info in the relevant locale folders; the descriptions for both weapons may require reconsideration; not sure about the naming policy for the gun safes upstream but I'd recommend capitalising the Vulcan and Adjutant if they're similarly capitalised in-game; like Hyenh said, you need to add them to the copyright for the Vulcan, and the meta.json file for the Adjutant is only for the spriter's copyright information, you don't need to note that you programmed it.

**Comment by TadJohnson00** [comment]
And just as a heads-up, I'd recommend ensuring you leave an extra blank line at the end of every document, just for consistency's sake.

**Comment by Jerryaqua** [comment]
I've fixed everything and im still having one last error with it, any advice?

**Comment by Colin-Tel** [comment]
> I've fixed everything and im still having one last error with it, any advice?

Both errors have nothing to do with the changes you've made.

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
