### PR TITLE
Adding scrubs to the Medidrobe

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR

This adds 2 of each scrub color to the Medidrobe

**Changelog**

:cl: VMSolidus
- add: Added scrubs to Medidrobe

### CODE REVIEW

**Comment by VMSolidus** [comment]
A small note. The code edits show up in the weird way that they do because I made this PR using the browser version of github, rather than the desktop version. After an extended discussion with Colin_Tel, we've found that this issue can be ignored.

**Comment by DebugOk** [comment]
> A small note. The code edits show up in the weird way that they do because I made this PR using the browser version of github, rather than the desktop version. After an extended discussion with Colin_Tel, we've found that this issue can be ignored. 

I do consider it an issue because it messes up the history, and removes the ability to blame on master

**Comment by VMSolidus** [comment]
Okay, then lets work out what I did wrong, and fix it. Heres what I did, following Github's own guide
- Used Gitbash to clone the repository and make my own fork
- Used visual studio to make the code changes
- Made a branch for said changes
- uploaded the changed file to this branch via the web client
- then made a PR using said branch

**Comment by DebugOk** [comment]
> Okay, then lets work out what I did wrong, and fix it. Heres what I did, following Github's own guide
> - Used Gitbash to clone the repository and make my own fork
> - Used visual studio to make the code changes
> - Made a branch for said changes
> - uploaded the changed file to this branch via the web client
> - then made a PR using said branch

That's your issue then, overwriting the file instead of pushing a proper diff

**Comment by VMSolidus** [comment]
Alright. How can I make a proper diff then? Would I instead edit the existing file directly via Git, as opposed to doing so with Visual Studio?

**Pull request closed without merging**
