### PR TITLE
ERT Overhaul

### PR DESCRIPTION
**Pull request by Tryded**
Overhauling ERTs that admemes can spawn.
Mostly Admeme QoL.

## About the PR

Completely Overhauls the Emergency Response Teams based off of Paradise Station's Wiki, dividing them into 3 levels, Amber, Red, and Gamma.
https://paradisestation.org/wiki/index.php?title=Emergency_Response_Team
Amber has no hardsuits and the ERT members are basically just like their job but a bit better.
Red and Gamma gets hardsuits and Gamma Level has multiple experimental equipment for when everything goes wrong.
This could allow admins to quickly set up Emergency Response Teams of their choosing while not running the risk of losing extremely overpowered gear.
Hopefully this would allow deployment of ERTs to ease times of crisis, for example during a mass bombing crisis and majority of the engineering department is dead or incompetent, instead of letting the station burn to the ground Central command would send an Amber ERT instead until the crisis is averted. 
**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

### CODE REVIEW

**Comment by Tryded** [comment]
Currently having problems with some ERT members missing bags and belts

**Comment by Tryded** [comment]
What does "   1) CLIENT: 0.223s [ERRO] root: Predicting the queued deletion of a networked entity: observer (27313, MobObserver). Trace:    at System.Environment.get_StackTrace()
It is the only failure in Build & Test Debug / build (ubuntu-latest) (pull request)

**Comment by Colin-Tel** [comment]
> What does " 1) CLIENT: 0.223s [ERRO] root: Predicting the queued deletion of a networked entity: observer (27313, MobObserver). Trace: at System.Environment.get_StackTrace() It is the only failure in Build & Test Debug / build (ubuntu-latest) (pull request)

image

Tests sometimes will fail for something completely unrelated to your changes.

**Comment by Tryded** [comment]
Welp time to wait for review

**Comment by DEATHB4DEFEAT** [comment]
Changelogs are unnecessary unless ERT is done without admin intervention now and I didn't notice

**Comment by Tryded** [comment]
Ah well, do I just delete them from existence?

**Review by DEATHB4DEFEAT — COMMENTED** [review]
SS13's Amber alert is pretty much equivalent to SS14's Red alert, and we don't have an Amber alert, so maybe shift the names around

**Comment by DEATHB4DEFEAT** [comment]
> Ah well, do I just delete them from existence?

Make sure the changes are covered in the PR description and you can delete the CL

**Comment by Tryded** [comment]
Amber is a custom name made for ERTs that are meant to more of give the station more personnel to help solve their problems, like a relief team.


> SS13's Amber alert is pretty much equivalent to SS14's Red alert, and we don't have an Amber alert, so maybe shift the names around

**Comment by Tryded** [comment]
> Amber is a custom name made for ERTs that are meant to more of give the station more personnel to help solve their problems, like a relief team.
> 
> > SS13's Amber alert is pretty much equivalent to SS14's Red alert, and we don't have an Amber alert, so maybe shift the names around

This is why they aren't armed to the teeth compared to the others. only enough to do their jobs.

**Comment by Tryded** [comment]
If anyone wants to add code so that different types of ERTs can be called via Comms console, be my guest.

**Comment by DebugOk** [comment]
> If anyone wants to add code so that different types of ERTs can be called via Comms console, be my guest.

Code like that will not be merged now or at any point in the future. Hard no.

**Comment by Tryded** [comment]
> > If anyone wants to add code so that different types of ERTs can be called via Comms console, be my guest.
> 
> Code like that will not be merged now or at any point in the future. Hard no.

Well, is this PR by itself fine? It only makes it so admenes can deploy ERTs easier without risking the loss of valuable equipment.

**Comment by Tryded** [comment]
> > If anyone wants to add code so that different types of ERTs can be called via Comms console, be my guest.
> 
> Code like that will not be merged now or at any point in the future. Hard no.

Well, it probably won't get coded, however I do want to know any objections with this PR

**Comment by Tryded** [comment]
Note: This PR is mostly just for admene QoL, it does not have anything that makes ERT spawn able without admin intervention.

**Comment by Tryded** [comment]
I wonder if this has a chance of getting approved

**Comment by Tryded** [comment]
pls review /hj

**Comment by DEATHB4DEFEAT** [comment]
the hell does `/hj` mean

**Comment by Tryded** [comment]
> the hell does `/hj` mean
half joking, eh probably shouldn't use it on github or something.

**Review by Colin-Tel — COMMENTED** [review]
Looks alright to me.

**Comment by Tryded** [comment]
> Looks alright to me.

So approved?

**Review by DEATHB4DEFEAT — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
