### PR TITLE
Updated epi clothes, Sophic Grammateus sprite, and new cocktail Dulleavene

### PR DESCRIPTION
**Pull request by leonardo-dabepis**
## About the PR

Changes the acolyte and mystagogue robes, adds a cloak for mystagogue, adds a sprite for the Sophic Grammateus, and adds a new cocktail called dulleavene

**Media**

image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Leonardo-DaBepis
- add: added cloak for mystagogue, new Sophic Grammateus sprite, new cocktail dulleavene.
- tweak: Changed the sprites for the acolyte and mystagogue robes.

### CODE REVIEW

**Comment by DebugOk** [comment]
Phil PR real!!1!

**Review by DebugOk — CHANGES_REQUESTED** [review]
When changing Nyano sprites, I think we should go for the approach of making a new sprite in the DeltaV namespace, instead of replacing files. (I'm guilty of this too with the Oracle:blunt:)

**Comment by leonardo-dabepis** [comment]
> When changing Nyano sprites, I think we should go for the approach of making a new sprite in the DeltaV namespace, instead of replacing files. (I'm guilty of this too with the Oracle:blunt:)

I learned it from you :elp: 
Do you want me to just make a new folder in DeltaV and redirect the .yml files there?

**Comment by DebugOk** [comment]
> > When changing Nyano sprites, I think we should go for the approach of making a new sprite in the DeltaV namespace, instead of replacing files. (I'm guilty of this too with the Oracle:blunt:)
> 
> I learned it from you :elp: 
> Do you want me to just make a new folder in DeltaV and redirect the .yml files there?

Pretty much. It can be all the same, except you have the files in /Textures/DeltaV or whatever it was. The .yml file shouldn't be moved, though. Only the sprites.

**Comment by leonardo-dabepis** [comment]
> > > When changing Nyano sprites, I think we should go for the approach of making a new sprite in the DeltaV namespace, instead of replacing files. (I'm guilty of this too with the Oracle:blunt:)
> > 
> > 
> > I learned it from you :elp:
> > Do you want me to just make a new folder in DeltaV and redirect the .yml files there?
> 
> Pretty much. It can be all the same, except you have the files in /Textures/DeltaV or whatever it was. The .yml file shouldn't be moved, though. Only the sprites.

Ok, I think I changed the sprite folder correctly. Did I?

**Comment by DebugOk** [comment]
I'll check when I get back on my pc

**Comment by DebugOk** [comment]
The robes should also be moved, and 2 merge conflicts have popped up on your branch which will need to be resolved first.

**Review by DebugOk — APPROVED** [review]
Checked in game, all looks good, except a weird space in the sophic prototype, however this doesnt matter as it'll be updated again soon to replace the npc dialogue tree. If tests pass I'll merge

**Comment by DebugOk** [comment]
>Tests failed
>Merging can be performed automatically.

I'll take it. The failures are unrelated anyways. Trying one more time and then I'll just merge it if its the exact same thing again

**Pull request merged**
