### PR TITLE
Cargo shotgun hotfix

### PR DESCRIPTION
**Pull request by Jerryaqua**
## About the PR

**Media**

- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

- fix: The new shotguns will now come in properly locked crates

### CODE REVIEW

**Comment by Hyenh** [comment]
These commits were already merged?

**Comment by DEATHB4DEFEAT** [comment]
reset your branch

**Comment by Jerryaqua** [comment]
Ah fuck why does this keep happning, how can I remove the last update, I didn't want to commit this to here

**Comment by Jerryaqua** [comment]
githib is SO hard to use damn it

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by DEATHB4DEFEAT** [comment]
> opened 7 days ago

This hot fix is quite cold

**Comment by DebugOk** [comment]
Issues fixed in #175

**Pull request closed without merging**
