### PR TITLE
Cherrypick 2023 05 06

### PR DESCRIPTION
**Pull request by Samsterious**
## About the PR
Merges most of the changes from Nyanotrasen since April 18ᵗʰ.

The following commits were *not* merged:
- [Update publish workflow for the new server #1515](https://www.github.com/Nyanotrasen/Nyanotrasen/pull/1515)
- [Get rid of mapped corpium on a salvage wreck #1473](https://www.github.com/Nyanotrasen/Nyanotrasen/pull/1473)

**Media**
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

### CODE REVIEW

**Comment by Elijahrane** [comment]
EDIT: Resolved the RedialAddresses.txt conversation in Discord

**Comment by Samsterious** [comment]
> Do you not intend to reciprocate redialing? That change was for the benefit of Delta-V.

Whoops! I didn't read the diff carefully and misunderstood what was going on there. Thanks for the catch!

**Comment by DebugOk** [comment]
Please avoid merging [disable atlas medical salvage (#1531)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/ff2a3fecf42ef199ba22a57354c52f797b2db301) and [Get rid of mapped corpium on a salvage wreck (#1473)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/7763166a0c5a5eecea2aed6b29a0cfb8a2fdc6c0)

One was made in response to the other being broken and deleting the map, you'd be best off avoiding to merge at least #1473 if you dont want corpium to be available until my other pr gets merged on nyano because its quite litteraly game breaking

**Comment by Samsterious** [comment]
> Please avoid merging [disable atlas medical salvage (#1531)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/ff2a3fecf42ef199ba22a57354c52f797b2db301) and [Get rid of mapped corpium on a salvage wreck (#1473)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/7763166a0c5a5eecea2aed6b29a0cfb8a2fdc6c0)
> 
> One was made in response to the other being broken and deleting the map, you'd be best off avoiding to merge at least #1473 if you dont want corpium to be available until my other pr gets merged on nyano because its quite litteraly game breaking

Sorry, I'm not fully understanding your words here. It sounds like you're saying one of these commits (which one?) is broken, and the other one was created to fix it?

**Comment by DebugOk** [comment]
[Get rid of mapped corpium on a salvage wreck (#1473)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/7763166a0c5a5eecea2aed6b29a0cfb8a2fdc6c0) has an improperly saved map, which breaks the game when loaded in the intended way. [disable atlas medical salvage (#1531)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/ff2a3fecf42ef199ba22a57354c52f797b2db301) was a rapid bandaid in response to said breaking

**Comment by Samsterious** [comment]
> [Get rid of mapped corpium on a salvage wreck (#1473)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/7763166a0c5a5eecea2aed6b29a0cfb8a2fdc6c0) has an improperly saved map, which breaks the game when loaded in the intended way. [disable atlas medical salvage (#1531)](https://github.com/DeltaV-Station/Delta-v/pull/3/commits/ff2a3fecf42ef199ba22a57354c52f797b2db301) was a rapid bandaid in response to said breaking

So, you propose removing #1473 and keeping #1531?

**Comment by DebugOk** [comment]
For the time being, yes. The made change was removing corpium from one salvage wreck, and leaving the map out of the salvage queue is fine for now.

I have an open PR on nyano that reverts #1531 and uses a properly saved grid. When thats merged you'd be better off nicking that

**Comment by Samsterious** [comment]
> For the time being, yes. The made change was removing corpium from one salvage wreck, and leaving the map out of the salvage queue is fine for now.
> 
> I have an open PR on nyano that reverts #1531 and uses a properly saved grid. When thats merged you'd be better off nicking that

There we go. Thanks for intervening, and for your clarification.

**Review by Colin-Tel — APPROVED** [review]

**Comment by ZeroDayDaemon** [comment]
This has been superseded by a full merge after Nyano's recent Wizard's Den merge

**Pull request closed without merging**
