### PR TITLE
Portafib - Portable Defibrillator (Properly)

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

The Portafib is a portable defibrillator for Paramedics or the Doctor on the go! It is a starting item for Paramedics, can be found in their locker, and one can also be purchased per refill of the NanoMed vending machine. It's inspired by my own experiences playing med roles, and is intended for civilian use.

The Portafib's primary purpose is to allow medical staff to keep a defibrillator on-hand without the extreme weight cost of the original, and without potentially taking one away from the medbay's limited stock. It works almost identically to the original, but in order to balance its portable nature, it uses up far more energy per zap, meaning on a small battery, it can only be used twice before requiring a recharge, significantly limiting its potential without returning to base. With a weight of 20 compared to the original's 50, it should allow paramedics to comfortably carry both a defib and a folded rollerbed without having nearly zero inventory space to spare whatsoever.

I actually wanted it to work more like a stun baton, where it must be charged directly and its battery cannot be swapped or upgraded, for balance reasons, keeping it at a permanent 3 uses per full recharge with no possibility of upgrading. However, I was unable to figure out how to code this, so if that's really essential for balance, I would appreciate having some help figuring out how to do that. (This is the first item I've ever tried adding to the game!)

The sprite itself is based on the existing fib, with the paddles, color, and design all tweaked to be more readable as a separate item, while keeping similar motifs to the original.

EDIT: Now PR'd on a branch correctly and no longer has sprites within upstream folders.

**Media**

https://github.com/DeltaV-Station/Delta-v/assets/52761126/72f4e837-b8f3-48c7-b287-cfaf527f6178

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: rosieposie
- add: Added the Portafib, a portable defibrillator which has more limited charge but weighs significantly less.

### CODE REVIEW

**Comment by Colin-Tel** [comment]
It doesn't looks like this will actually appear in-game. This PR doesn't change the contents of a Paramedic's starting gear, nor does it add this item to their lockers.

This PR lacks some of the inclusions in the previous PR you closed that would have it included in said containers.

**Comment by rosieposieeee** [comment]
Ah shit I must have must those files. Will add them back.

**Review by DebugOk — CHANGES_REQUESTED** [review]
Test failure is valid, cant merge

**Comment by Colin-Tel** [comment]
image
Yeah, a size 20 Portafib isn't fitting in the paramedic belt. This should probably be corrected by removing a couple things from it.

**Comment by DebugOk** [comment]
> image Yeah, a size 20 Portafib isn't fitting in the paramedic belt. This should probably be corrected by removing a couple things from it.

A whole ass defib shouldn't go in a belt anyways

**Comment by rosieposieeee** [comment]
Sorry, I forgot about this one a little bit. Took it out of the belt and put it in the bag, should all be good now.

**Comment by rosieposieeee** [comment]
your FACE has conflicts. (fixed the conflicts)

**Pull request closed without merging**
