### PR TITLE
Update angle.yml

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Completely overhauled Angle's medical department.

This is an early merge of the following upstream PR: https://github.com/Nyanotrasen/Nyanotrasen/pull/1791

**Media**

Angle-0

**Changelog**
:cl:
- tweak: The Angle Rig's medical department has been completely overhauled according to new NT Corporate standards.

### CODE REVIEW

**Review by DebugOk — DISMISSED** [review]

**Comment by Colin-Tel** [comment]
one moment don't merge

**Comment by Colin-Tel** [comment]
Okay it's fixed lol

**Comment by Colin-Tel** [comment]
shit nevermind it's not fixed, hang on again

**Comment by Colin-Tel** [comment]
Fixed the missing disposal pipes

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
